### PR TITLE
Reimport

### PR DESCRIPTION
**Pull request by martinwe-adfinis**
Split from our internal playbooks repository.

Keep in mind that this role is currently not meant for general use, but simply needs to be shared across two (potentially more, later) playbooks.

### CODE REVIEW

**Comment by martinwe-adfinis** [comment]
Should probably add a disclaimer in the readme that this role is not meant for general use.

Also, a [codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to assign this repo to me.

**Comment by martinwe-adfinis** [comment]
Added `.github/CODEOWNERS`, I hope this works.

**Review by ghost — APPROVED** [review]

**Comment by martinwe-adfinis** [comment]
Thanks!

**--edit**: Currently waiting for admin permissions on repo, before merging this and making my ownership/responsibility for this code official.

**Comment by hairmare** [comment]
@martinwe-adfinis feel free to ping me if you need me to wield the orga-owner-staff to grant you additional rights

**Comment by martinwe-adfinis** [comment]
Thanks to everyone! Merging this now.

**Pull request merged**
