### PR TITLE
skip lint 405

### PR DESCRIPTION
**Pull request by eyenx**
##### SUMMARY
ansible-lint doesn't work anymore. @fujexo and I run into this issue with our respective roles.

##### ISSUE TYPE
 - Bugfix Pull Request

##### ANSIBLE VERSION

```
2.7.4
```

##### ADDITIONAL INFORMATION
By skipping the 405 check, the build works.

### CODE REVIEW

**Comment by eyenx** [comment]
This will not only be a issue for this repo, but we think for every single role we have.

**Review by fujexo — APPROVED** [review]
LGTM

**Comment by hairmare** [comment]
If this affects every role, is it really sane to deactivate this on each and everyone?

I didn't take a close look but https://github.com/ansible/ansible-lint/issues/405 seems to have some PRs that linking to it that might have hints on how to fix, rather than ignore the issue... Maybe we just need to update ansible-lint?

**Comment by eyenx** [comment]
I don't see how we can fix this without adding something like

https://github.com/awcrosby/ansible-lint/blob/650624eeaaf29daf87960544668a43720737399d/test/TestPackageHasRetry.py#L14

Into every installation.yml that does some package installation.

**Pull request merged**
